analyzer:
  exclude:
    - build/**
    - android/**
    - ios/**
    - web/**
    - windows/**
linter:
  rules:
    - prefer_const_constructors
    - avoid_print
    - use_build_context_synchronously
    - sort_child_properties_last